# OpenEvolve Configuration for OpenRouter
# This configuration uses OpenRouter API for LLM access

# General settings
max_iterations: 50                  # Maximum number of evolution iterations
checkpoint_interval: 10             # Save checkpoints every N iterations
log_level: "INFO"                   # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
random_seed: 42                     # Random seed for reproducibility

# Evolution settings
diff_based_evolution: true          # Use diff-based evolution (true) or full rewrites (false)
max_code_length: 10000              # Maximum allowed code length in characters

# LLM configuration
llm:
  # Models for evolution
  models:
    # Using Claude model via OpenRouter
    - name: "anthropic/claude-3-haiku"
      weight: 1.0

  # Models for LLM feedback
  evaluator_models:
    # Using Claude model via OpenRouter
    - name: "anthropic/claude-3-haiku"
      weight: 1.0

  # API configuration
  api_base: "https://openrouter.ai/api/v1"  # OpenRouter API base URL
  api_key: null                             # Will use OPENAI_API_KEY env variable

  # Generation parameters
  temperature: 0.7                    # Temperature for generation (higher = more creative)
  top_p: 0.95                         # Top-p sampling parameter
  max_tokens: 4096                    # Maximum tokens to generate

  # Request parameters
  timeout: 60                         # Timeout for API requests in seconds
  retries: 3                          # Number of retries for failed requests
  retry_delay: 5                      # Delay between retries in seconds

# Prompt configuration
prompt:
  system_message: "You are an expert coder helping to improve programs through evolution."
  evaluator_system_message: "You are an expert code reviewer."

  # Number of examples to include in the prompt
  num_top_programs: 3                 # Number of top-performing programs to include
  num_diverse_programs: 2             # Number of diverse programs to include

# Database configuration
database:
  in_memory: true                     # Keep database in memory for faster access
  log_prompts: true                   # If true, log all prompts and responses into the database

  # Evolutionary parameters
  population_size: 100                # Maximum number of programs to keep in memory
  archive_size: 20                    # Size of elite archive
  num_islands: 3                      # Number of islands for island model (separate populations)

# Evaluator configuration
evaluator:
  timeout: 30                         # Maximum evaluation time in seconds
  max_retries: 3                      # Maximum number of retries for evaluation
  parallel_evaluations: 4             # Number of parallel evaluations